---
- name: ensure cloudformation stack is created or deleted
  cloudformation:
    stack_name: "{{ config.project_name }}"
    state: "{{ stack_state }}"
    region: "{{ config.aws_region }}"
    template: "{{ playbook_dir }}/cfn-template.yml"
    stack_policy: "{{ playbook_dir }}/cfn-policy.json"
    template_parameters:
      AccountName: "{{ account_name }}"
      RecipientEmailAddress: "{{ recipient_email }}"
      MaxMonthlyExpenseInDollars: "{{ max_expense_in_dollars }}"
    tags:
      project: "{{ config.project_name }}"
      owner: "{{ config.project_owner }}"
      lifetime: "{{ config.project_lifetime }}"

