---
# What is the name of the project?  This value is used as the stack name
# and in other components.
project_name: 'billing-alerts'

# What team is responsible for managing this stack?
project_owner: "infra"

# Is this stack long-lived or short-lived within this AWS account?
project_lifetime: "long"

# AWS region where the stack will reside.
# Billing alarms must reside in us-east-1, according to docs.
# Doc: http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/free-tier-alarms.html
aws_region: "us-east-1"

